<?xml version='1.0' encoding='UTF-8'?>

<!DOCTYPE classements_joueur [
<!ELEMENT classements_joueur (joueur+)>
<!ELEMENT joueur (nom, nb_ennemis_tues, distance, or, temps, score, difficulte)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT nb_ennemis_tues (#PCDATA)>
<!ELEMENT distance (#PCDATA)>
<!ELEMENT or (#PCDATA)>
<!ELEMENT temps (#PCDATA)>
<!ELEMENT score (#PCDATA)>
<!ELEMENT difficulte (#PCDATA)>
]>

<classements_joueur><joueur><nom>ludovic</nom><nb_ennemis_tues>5</nb_ennemis_tues><distance>69</distance><or>53</or><temps>197.451294</temps><score>2369</score><difficulte>Novice</difficulte></joueur><joueur><nom>ludovic</nom><nb_ennemis_tues>5</nb_ennemis_tues><distance>69</distance><or>53</or><temps>184.859574</temps><score>2369</score><difficulte>Novice</difficulte></joueur><joueur><nom>ludovic</nom><nb_ennemis_tues>5</nb_ennemis_tues><distance>69</distance><or>53</or><temps>196.380233</temps><score>2369</score><difficulte>Novice</difficulte></joueur><joueur><nom>ludovic</nom><nb_ennemis_tues>5</nb_ennemis_tues><distance>71</distance><or>53</or><temps>464.129546</temps><score>2436</score><difficulte>Novice</difficulte></joueur><joueur><nom>ludovic</nom><nb_ennemis_tues>5</nb_ennemis_tues><distance>71</distance><or>53</or><temps>555.401767</temps><score>2436</score><difficulte>Novice</difficulte></joueur><joueur><nom>ludovic</nom><nb_ennemis_tues>18</nb_ennemis_tues><distance>234</distance><or>153</or><temps>861.831292</temps><score>8013</score><difficulte>Novice</difficulte></joueur><joueur><nom>ludoMoyen</nom><nb_ennemis_tues>2</nb_ennemis_tues><distance>32</distance><or>84</or><temps>72.220131</temps><score>1694</score><difficulte>Moyen</difficulte></joueur><joueur><nom>ludovic</nom><nb_ennemis_tues>5</nb_ennemis_tues><distance>70</distance><or>53</or><temps>470.262897</temps><score>2403</score><difficulte>Novice</difficulte></joueur><joueur><nom>T</nom><nb_ennemis_tues>3</nb_ennemis_tues><distance>75</distance><or>24</or><temps>57.152258</temps><score>7554</score><difficulte>Expert</difficulte></joueur><joueur><nom>dragon</nom><nb_ennemis_tues>1</nb_ennemis_tues><distance>23</distance><or>0</or><temps>83.228554</temps><score>2310</score><difficulte>Expert</difficulte></joueur><joueur><nom/><nb_ennemis_tues>2</nb_ennemis_tues><distance>28</distance><or>35</or><temps>223.213819</temps><score>975</score><difficulte>Novice</difficulte></joueur><joueur><nom>zae</nom><nb_ennemis_tues>0</nb_ennemis_tues><distance>15</distance><or>0</or><temps>57.190262</temps><score>1500</score><difficulte>Expert</difficulte></joueur><joueur><nom>JoueurInconnu</nom><nb_ennemis_tues>0</nb_ennemis_tues><distance>1</distance><or>0</or><temps>6.425367</temps><score>33</score><difficulte>Novice</difficulte></joueur></classements_joueur>