<?xml version = "1.0" encoding="UTF-8" standalone="yes" ?>

<!DOCTYPE difficultes [
<!ELEMENT difficultes (difficulte+)>
<!ELEMENT difficulte (intitule, longueurCarte, largeurCarte, energieDepart, nbRepos, pnjAmisDepart, pnjEnnemisDepart, pnjEnnemisParGeneration, objetsDepart, objetsParGeneration, nbToursInterGenerations, pourcentageTerrain)>
<!ELEMENT intitule (#PCDATA)>
<!ELEMENT longueurCarte (#PCDATA)>
<!ELEMENT largeurCarte (#PCDATA)>
<!ELEMENT energieDepart (#PCDATA)>
<!ELEMENT nbRepos (#PCDATA)>
<!ELEMENT pnjAmisDepart (#PCDATA)>
<!ELEMENT pnjEnnemisDepart (#PCDATA)>
<!ELEMENT pnjEnnemisParGeneration (#PCDATA)>
<!ELEMENT objetsDepart (#PCDATA)>
<!ELEMENT objetsParGeneration (#PCDATA)>
<!ELEMENT nbToursInterGenerations (#PCDATA)>
<!ELEMENT pourcentageTerrain (#PCDATA)>
]>

<difficultes>

	<difficulte>
	    <intitule>Novice</intitule>
	    <longueurCarte>40</longueurCarte>
	    <largeurCarte>40</largeurCarte>
	    <energieDepart>1000</energieDepart>
	    <nbRepos>15</nbRepos>
	    <pnjAmisDepart>105</pnjAmisDepart>
	    <pnjEnnemisDepart>105</pnjEnnemisDepart>
	    <pnjEnnemisParGeneration>2</pnjEnnemisParGeneration>
	    <objetsDepart>50</objetsDepart>
	    <objetsParGeneration>1</objetsParGeneration>
	    <nbToursInterGenerations>10</nbToursInterGenerations>
	    <pourcentageTerrain>1</pourcentageTerrain>
	</difficulte>
	<difficulte>
	    <intitule>Moyen</intitule>
	    <longueurCarte>60</longueurCarte>
	    <largeurCarte>60</largeurCarte>
	    <energieDepart>1000</energieDepart>
	    <nbRepos>10</nbRepos>
	    <pnjAmisDepart>150</pnjAmisDepart>
	    <pnjEnnemisDepart>300</pnjEnnemisDepart>
	    <pnjEnnemisParGeneration>5</pnjEnnemisParGeneration>
	    <objetsDepart>100</objetsDepart>
	    <objetsParGeneration>2</objetsParGeneration>
	    <nbToursInterGenerations>10</nbToursInterGenerations>
	    <pourcentageTerrain>1.2</pourcentageTerrain>
	</difficulte>
	<difficulte>
	    <intitule>Expert</intitule>
	    <longueurCarte>100</longueurCarte>
	    <largeurCarte>100</largeurCarte>
	    <energieDepart>1000</energieDepart>
	    <nbRepos>5</nbRepos>
	    <pnjAmisDepart>300</pnjAmisDepart>
	    <pnjEnnemisDepart>600</pnjEnnemisDepart>
	    <pnjEnnemisParGeneration>15</pnjEnnemisParGeneration>
	    <objetsDepart>200</objetsDepart>
	    <objetsParGeneration>5</objetsParGeneration>
	    <nbToursInterGenerations>15</nbToursInterGenerations>
	    <pourcentageTerrain>1.4</pourcentageTerrain>
	</difficulte>

</difficultes>


