<?xml version = "1.0" encoding="UTF-8" standalone="yes" ?>

<!DOCTYPE ref_graphiques [
<!ELEMENT ref_graphiques (reference+)>
<!ELEMENT reference (intitule_objet, img_ihm)>
<!ELEMENT intitule_objet (#PCDATA)>
<!ELEMENT img_ihm (#PCDATA)>
]>

<ref_graphiques>

<reference>
   <intitule_objet>itemSelect</intitule_objet>
   <img_ihm>./img/gui/coloris_noir.png</img_ihm>
</reference>

<reference>
   <intitule_objet>gauche</intitule_objet>
   <img_ihm>./img/gui/gauche.png</img_ihm>
</reference>

<reference>
   <intitule_objet>haut</intitule_objet>
   <img_ihm>./img/gui/haut.png</img_ihm>
</reference>

<reference>
   <intitule_objet>bas</intitule_objet>
   <img_ihm>./img/gui/bas.png</img_ihm>
</reference>

<reference>
   <intitule_objet>droite</intitule_objet>
   <img_ihm>./img/gui/droite.png</img_ihm>
</reference>

<reference>
   <intitule_objet>montagne</intitule_objet>
   <img_ihm>./img/terrain/rocher.png</img_ihm>
</reference>
<reference>
   <intitule_objet>montagne_bordureN</intitule_objet>
   <img_ihm>./img/terrain/montagne_bordureN.png</img_ihm>
</reference>
<reference>
   <intitule_objet>montagne_bordureS</intitule_objet>
   <img_ihm>./img/terrain/montagne_bordureS.png</img_ihm>
</reference>
<reference>
   <intitule_objet>montagne_bordureE</intitule_objet>
   <img_ihm>./img/terrain/montagne_bordureE.png</img_ihm>
</reference>
<reference>
   <intitule_objet>montagne_bordureO</intitule_objet>
   <img_ihm>./img/terrain/montagne_bordureO.png</img_ihm>
</reference>

<reference>
   <intitule_objet>desert</intitule_objet>
   <img_ihm>./img/terrain/sable.png</img_ihm>
</reference>
<reference>
   <intitule_objet>desert_bordureN</intitule_objet>
   <img_ihm>./img/terrain/desert_bordureN.png</img_ihm>
</reference>
<reference>
   <intitule_objet>desert_bordureS</intitule_objet>
   <img_ihm>./img/terrain/desert_bordureS.png</img_ihm>
</reference>
<reference>
   <intitule_objet>desert_bordureE</intitule_objet>
   <img_ihm>./img/terrain/desert_bordureE.png</img_ihm>
</reference>
<reference>
   <intitule_objet>desert_bordureO</intitule_objet>
   <img_ihm>./img/terrain/desert_bordureO.png</img_ihm>
</reference>

<reference>
   <intitule_objet>eau</intitule_objet>
   <img_ihm>./img/terrain/eau.png</img_ihm>
</reference>
<reference>
   <intitule_objet>eau_bordureN</intitule_objet>
   <img_ihm>./img/terrain/eau_bordureN.png</img_ihm>
</reference>
<reference>
   <intitule_objet>eau_bordureS</intitule_objet>
   <img_ihm>./img/terrain/eau_bordureS.png</img_ihm>
</reference>
<reference>
   <intitule_objet>eau_bordureE</intitule_objet>
   <img_ihm>./img/terrain/eau_bordureE.png</img_ihm>
</reference>
<reference>
   <intitule_objet>eau_bordureO</intitule_objet>
   <img_ihm>./img/terrain/eau_bordureO.png</img_ihm>
</reference>

<reference>
   <intitule_objet>plaine</intitule_objet>
   <img_ihm>./img/terrain/plaine.png</img_ihm>
</reference>
<reference>
   <intitule_objet>plaine_bordureN</intitule_objet>
   <img_ihm>./img/terrain/plaine_bordureN.png</img_ihm>
</reference>
<reference>
   <intitule_objet>plaine_bordureS</intitule_objet>
   <img_ihm>./img/terrain/plaine_bordureS.png</img_ihm>
</reference>
<reference>
   <intitule_objet>plaine_bordureE</intitule_objet>
   <img_ihm>./img/terrain/plaine_bordureE.png</img_ihm>
</reference>
<reference>
   <intitule_objet>plaine_bordureO</intitule_objet>
   <img_ihm>./img/terrain/plaine_bordureO.png</img_ihm>
</reference>

<reference>
   <intitule_objet>foret</intitule_objet>
   <img_ihm>./img/terrain/foret.png</img_ihm>
</reference>
<reference>
   <intitule_objet>foret_bordureN</intitule_objet>
   <img_ihm>./img/terrain/foret_bordureN.png</img_ihm>
</reference>
<reference>
   <intitule_objet>foret_bordureS</intitule_objet>
   <img_ihm>./img/terrain/foret_bordureS.png</img_ihm>
</reference>
<reference>
   <intitule_objet>foret_bordureE</intitule_objet>
   <img_ihm>./img/terrain/foret_bordureE.png</img_ihm>
</reference>
<reference>
   <intitule_objet>foret_bordureO</intitule_objet>
   <img_ihm>./img/terrain/foret_bordureO.png</img_ihm>
</reference>

<reference>
   <intitule_objet>icone or</intitule_objet>
   <img_ihm>./img/gui/or.png</img_ihm>
</reference>

<reference>
   <intitule_objet>repos</intitule_objet>
   <img_ihm>./img/gui/repos.png</img_ihm>
</reference>

<reference>
   <intitule_objet>joueurN</intitule_objet>
   <img_ihm>./img/joueur/joueurN.png</img_ihm>
</reference>

<reference>
   <intitule_objet>joueurS</intitule_objet>
   <img_ihm>./img/joueur/joueurS.png</img_ihm>
</reference>

<reference>
   <intitule_objet>joueurE</intitule_objet>
   <img_ihm>./img/joueur/joueurE.png</img_ihm>
</reference>

<reference>
   <intitule_objet>joueurO</intitule_objet>
   <img_ihm>./img/joueur/joueurO.png</img_ihm>
</reference>
<reference>
   <intitule_objet>joueurNb</intitule_objet>
   <img_ihm>./img/joueur/joueurNb.png</img_ihm>
</reference>

<reference>
   <intitule_objet>joueurSb</intitule_objet>
   <img_ihm>./img/joueur/joueurSb.png</img_ihm>
</reference>

<reference>
   <intitule_objet>joueurEb</intitule_objet>
   <img_ihm>./img/joueur/joueurEb.png</img_ihm>
</reference>

<reference>
   <intitule_objet>joueurOb</intitule_objet>
   <img_ihm>./img/joueur/joueurOb.png</img_ihm>
</reference>

<reference>
   <intitule_objet>chauve-sourisN</intitule_objet>
   <img_ihm>./img/ennemi/chauve_sourisN.png</img_ihm>
</reference>

<reference>
   <intitule_objet>chauve-sourisS</intitule_objet>
   <img_ihm>./img/ennemi/chauve_sourisS.png</img_ihm>
</reference>

<reference>
   <intitule_objet>chauve-sourisE</intitule_objet>
   <img_ihm>./img/ennemi/chauve_sourisE.png</img_ihm>
</reference>

<reference>
   <intitule_objet>chauve-sourisO</intitule_objet>
   <img_ihm>./img/ennemi/chauve_sourisO.png</img_ihm>
</reference>
<reference>
   <intitule_objet>chauve-sourisNb</intitule_objet>
   <img_ihm>./img/ennemi/chauve_sourisNb.png</img_ihm>
</reference>

<reference>
   <intitule_objet>chauve-sourisSb</intitule_objet>
   <img_ihm>./img/ennemi/chauve_sourisSb.png</img_ihm>
</reference>

<reference>
   <intitule_objet>chauve-sourisEb</intitule_objet>
   <img_ihm>./img/ennemi/chauve_sourisEb.png</img_ihm>
</reference>

<reference>
   <intitule_objet>chauve-sourisOb</intitule_objet>
   <img_ihm>./img/ennemi/chauve_sourisOb.png</img_ihm>
</reference>

<reference>
   <intitule_objet>loupN</intitule_objet>
   <img_ihm>./img/ennemi/loupN.png</img_ihm>
</reference>

<reference>
   <intitule_objet>loupS</intitule_objet>
   <img_ihm>./img/ennemi/loupS.png</img_ihm>
</reference>

<reference>
   <intitule_objet>loupE</intitule_objet>
   <img_ihm>./img/ennemi/loupE.png</img_ihm>
</reference>

<reference>
   <intitule_objet>loupO</intitule_objet>
   <img_ihm>./img/ennemi/loupO.png</img_ihm>
</reference>
<reference>
   <intitule_objet>loupNb</intitule_objet>
   <img_ihm>./img/ennemi/loupNb.png</img_ihm>
</reference>

<reference>
   <intitule_objet>loupSb</intitule_objet>
   <img_ihm>./img/ennemi/loupSb.png</img_ihm>
</reference>

<reference>
   <intitule_objet>loupEb</intitule_objet>
   <img_ihm>./img/ennemi/loupEb.png</img_ihm>
</reference>

<reference>
   <intitule_objet>loupOb</intitule_objet>
   <img_ihm>./img/ennemi/loupOb.png</img_ihm>
</reference>

<reference>
   <intitule_objet>brigandN</intitule_objet>
   <img_ihm>./img/ennemi/brigandN.png</img_ihm>
</reference>

<reference>
   <intitule_objet>brigandS</intitule_objet>
   <img_ihm>./img/ennemi/brigandS.png</img_ihm>
</reference>

<reference>
   <intitule_objet>brigandE</intitule_objet>
   <img_ihm>./img/ennemi/brigandE.png</img_ihm>
</reference>

<reference>
   <intitule_objet>brigandO</intitule_objet>
   <img_ihm>./img/ennemi/brigandO.png</img_ihm>
</reference>
<reference>
   <intitule_objet>brigandNb</intitule_objet>
   <img_ihm>./img/ennemi/brigandNb.png</img_ihm>
</reference>

<reference>
   <intitule_objet>brigandSb</intitule_objet>
   <img_ihm>./img/ennemi/brigandSb.png</img_ihm>
</reference>

<reference>
   <intitule_objet>brigandEb</intitule_objet>
   <img_ihm>./img/ennemi/brigandEb.png</img_ihm>
</reference>

<reference>
   <intitule_objet>brigandOb</intitule_objet>
   <img_ihm>./img/ennemi/brigandOb.png</img_ihm>
</reference>

<reference>
   <intitule_objet>soldatN</intitule_objet>
   <img_ihm>./img/ennemi/soldatN.png</img_ihm>
</reference>

<reference>
   <intitule_objet>soldatS</intitule_objet>
   <img_ihm>./img/ennemi/soldatS.png</img_ihm>
</reference>

<reference>
   <intitule_objet>soldatE</intitule_objet>
   <img_ihm>./img/ennemi/soldatE.png</img_ihm>
</reference>

<reference>
   <intitule_objet>soldatO</intitule_objet>
   <img_ihm>./img/ennemi/soldatO.png</img_ihm>
</reference>
<reference>
   <intitule_objet>soldatNb</intitule_objet>
   <img_ihm>./img/ennemi/soldatNb.png</img_ihm>
</reference>

<reference>
   <intitule_objet>soldatSb</intitule_objet>
   <img_ihm>./img/ennemi/soldatSb.png</img_ihm>
</reference>

<reference>
   <intitule_objet>soldatEb</intitule_objet>
   <img_ihm>./img/ennemi/soldatEb.png</img_ihm>
</reference>

<reference>
   <intitule_objet>soldatOb</intitule_objet>
   <img_ihm>./img/ennemi/soldatOb.png</img_ihm>
</reference>

<reference>
   <intitule_objet>ogreN</intitule_objet>
   <img_ihm>./img/ennemi/ogreN.png</img_ihm>
</reference>

<reference>
   <intitule_objet>ogreS</intitule_objet>
   <img_ihm>./img/ennemi/ogreS.png</img_ihm>
</reference>

<reference>
   <intitule_objet>ogreE</intitule_objet>
   <img_ihm>./img/ennemi/ogreE.png</img_ihm>
</reference>

<reference>
   <intitule_objet>ogreO</intitule_objet>
   <img_ihm>./img/ennemi/ogreO.png</img_ihm>
</reference>
<reference>
   <intitule_objet>ogreNb</intitule_objet>
   <img_ihm>./img/ennemi/ogreNb.png</img_ihm>
</reference>

<reference>
   <intitule_objet>ogreSb</intitule_objet>
   <img_ihm>./img/ennemi/ogreSb.png</img_ihm>
</reference>

<reference>
   <intitule_objet>ogreEb</intitule_objet>
   <img_ihm>./img/ennemi/ogreEb.png</img_ihm>
</reference>

<reference>
   <intitule_objet>ogreOb</intitule_objet>
   <img_ihm>./img/ennemi/ogreOb.png</img_ihm>
</reference>

<reference>
   <intitule_objet>bottes en cuir</intitule_objet>
   <img_ihm>./img/item/bottes_cuir.png</img_ihm>
</reference>

<reference>
   <intitule_objet>bottes en fer</intitule_objet>
   <img_ihm>./img/item/bottes_fer.png</img_ihm>
</reference>

<reference>
   <intitule_objet>bottes en acier</intitule_objet>
   <img_ihm>./img/item/bottes_acier.png</img_ihm>
</reference>

<reference>
   <intitule_objet>armure en cuir</intitule_objet>
   <img_ihm>./img/item/armure_cuir.png</img_ihm>
</reference>

<reference>
   <intitule_objet>armure en fer</intitule_objet>
   <img_ihm>./img/item/armure_fer.png</img_ihm>
</reference>

<reference>
   <intitule_objet>armure en acier</intitule_objet>
   <img_ihm>./img/item/armure_acier.png</img_ihm>
</reference>

<reference>
   <intitule_objet>epee en bois</intitule_objet>
   <img_ihm>./img/item/epee_bois.png</img_ihm>
</reference>

<reference>
   <intitule_objet>epee en fer</intitule_objet>
   <img_ihm>./img/item/epee_fer.png</img_ihm>
</reference>

<reference>
   <intitule_objet>epee en acier</intitule_objet>
   <img_ihm>./img/item/epee_acier.png</img_ihm>
</reference>

<reference>
   <intitule_objet>bout de pain</intitule_objet>
   <img_ihm>./img/item/pain.png</img_ihm>
</reference>

<reference>
   <intitule_objet>brocolie vapeur</intitule_objet>
   <img_ihm>./img/item/brocoli.png</img_ihm>
</reference>

<reference>
   <intitule_objet>steack de dinde</intitule_objet>
   <img_ihm>./img/item/steack_dinde.png</img_ihm>
</reference>

<reference>
   <intitule_objet>pavé d'émeu</intitule_objet>
   <img_ihm>./img/item/pave_emeu.png</img_ihm>
</reference>

<reference>
   <intitule_objet>poulet rôti</intitule_objet>
   <img_ihm>./img/item/poulet.png</img_ihm>
</reference>

<reference>
   <intitule_objet>marchand</intitule_objet>
   <img_ihm>./img/ami/marchand.png</img_ihm>
</reference>

<reference>
   <intitule_objet>guerisseur</intitule_objet>
   <img_ihm>./img/ami/guerisseur.png</img_ihm>
</reference>

<reference>
   <intitule_objet>bourse</intitule_objet>
   <img_ihm>./img/item/sac_or.png</img_ihm>
</reference>

<reference>
   <intitule_objet>blanc</intitule_objet>
   <img_ihm>./img/gui/blanc.jpg</img_ihm>
</reference>	
<reference>
   <intitule_objet>tombe</intitule_objet>
   <img_ihm>./img/joueur/tombe.png</img_ihm>
</reference>
<reference>
   <intitule_objet>dormeur</intitule_objet>
   <img_ihm>./img/joueur/dormeur.png</img_ihm>
</reference>
	
	
	
	

</ref_graphiques>
