<?xml version = "1.0" encoding="UTF-8" standalone="yes" ?>

<!DOCTYPE types_equipables [
<!ELEMENT types_equipables (type+)>
<!ELEMENT type (intitule, pourcentageProtection, nbTours, prix, sePorteSur,rarete)>
<!ELEMENT intitule (#PCDATA)>
<!ELEMENT pourcentageProtection (#PCDATA)>
<!ELEMENT nbTours (#PCDATA)>
<!ELEMENT prix (#PCDATA)>
<!ELEMENT sePorteSur (#PCDATA)>
]>

<types_equipables>

	<type>
	   <intitule>bottes en cuir</intitule>
	   <pourcentageProtection>0.10</pourcentageProtection>
	   <nbTours>5</nbTours>
	   <prix>10</prix>
	   <sePorteSur>3</sePorteSur>
	   <rarete>1</rarete>
	</type>
	<type>
	   <intitule>bottes en fer</intitule>
	   <pourcentageProtection>0.40</pourcentageProtection>
	   <nbTours>8</nbTours>
	   <prix>30</prix>
	   <sePorteSur>3</sePorteSur>
	   <rarete>2</rarete>
	</type>
	<type>
	   <intitule>bottes en acier</intitule>
	   <pourcentageProtection>0.70</pourcentageProtection>
	   <nbTours>10</nbTours>
	   <prix>50</prix>
	   <sePorteSur>3</sePorteSur>
	   <rarete>3</rarete>
	</type>
	<type>
	   <intitule>armure en cuir</intitule>
	   <pourcentageProtection>0.10</pourcentageProtection>
	   <nbTours>1</nbTours>
	   <prix>20</prix>
	   <sePorteSur>1</sePorteSur>
	   <rarete>1</rarete>
	</type>
	<type>
	   <intitule>armure en fer</intitule>
	   <pourcentageProtection>0.40</pourcentageProtection>
	   <nbTours>1</nbTours>
	   <prix>50</prix>
	   <sePorteSur>1</sePorteSur>
	   <rarete>2</rarete>
	</type>
	<type>
	   <intitule>armure en acier</intitule>
	   <pourcentageProtection>0.70</pourcentageProtection>
	   <nbTours>1</nbTours>
	   <prix>70</prix>
	   <sePorteSur>1</sePorteSur>
	   <rarete>3</rarete>
	</type>
	<type>
	   <intitule>epee en bois</intitule>
	   <pourcentageProtection>0.10</pourcentageProtection>
	   <nbTours>1</nbTours>
	   <prix>15</prix>
	   <sePorteSur>2</sePorteSur>
	   <rarete>1</rarete>
	</type>
	<type>
	   <intitule>epee en fer</intitule>
	   <pourcentageProtection>0.40</pourcentageProtection>
	   <nbTours>1</nbTours>
	   <prix>45</prix>
	   <sePorteSur>2</sePorteSur>
	   <rarete>2</rarete>
	</type>
	<type>
	   <intitule>epee en acier</intitule>
	   <pourcentageProtection>0.70</pourcentageProtection>
	   <nbTours>1</nbTours>
	   <prix>65</prix>
	   <sePorteSur>2</sePorteSur>
	   <rarete>3</rarete>
	</type>
	

</types_equipables>
