<?xml version = "1.0" encoding="UTF-8" standalone="yes" ?>

<!DOCTYPE types_mangeables [
<!ELEMENT types_mangeables (type+)>
<!ELEMENT type (intitule, energieRendue, prix, rarete)>
<!ELEMENT intitule (#PCDATA)>
<!ELEMENT energieRendue (#PCDATA)>
<!ELEMENT prix (#PCDATA)>
]>

<types_mangeables>

   <type>
      <intitule>bout de pain</intitule>
      <energieRendue>70</energieRendue>
      <prix>5</prix>
      <rarete>1</rarete>
   </type>
   <type>
      <intitule>brocolie vapeur</intitule>
      <energieRendue>100</energieRendue>
      <prix>10</prix>
      <rarete>1</rarete>
   </type>
   <type>
      <intitule>steack de dinde</intitule>
      <energieRendue>200</energieRendue>
      <prix>25</prix>
      <rarete>2</rarete>
   </type>
   <type>
      <intitule>pavé d'émeu</intitule>
      <energieRendue>500</energieRendue>
      <prix>50</prix>
      <rarete>3</rarete>
   </type>
   <type>
      <intitule>poulet rôti</intitule>
      <energieRendue>800</energieRendue>
      <prix>100</prix>
      <rarete>3</rarete>
   </type>
   



</types_mangeables>
