<?xml version = "1.0" encoding="UTF-8" standalone="yes" ?>

<!DOCTYPE types_ennemis [
<!ELEMENT types_ennemis (type+)>
<!ELEMENT type (intitule, energieBase)>
<!ELEMENT intitule (#PCDATA)>
<!ELEMENT energieBase (#PCDATA)>
]>

<types_ennemis>

	<type>
	   <intitule>chauve-souris</intitule>
	   <energieBase>30</energieBase>
	</type>
	<type>
	   <intitule>loup</intitule>
	   <energieBase>50</energieBase>
	</type>
	<type>
	   <intitule>brigand</intitule>
	   <energieBase>90</energieBase>
	</type>
	<type>
	   <intitule>soldat</intitule>
	   <energieBase>150</energieBase>
	</type>
	<type>
	   <intitule>ogre</intitule>
	   <energieBase>210</energieBase>
	</type>
	

</types_ennemis>
